name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"

env:
  TERM: xterm-256color
  IMAGE_PLATFORMS: "linux/amd64,linux/arm64"
  IMAGE_REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  BRANCH_OR_TAG: ${{ github.event.pull_request.head.ref || github.ref_name }}
  IS_MAIN: ${{ github.ref_name == 'main' }}
  IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}

jobs:
  build-n-push:
    name: Build and push
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Set up QEMU
        if: contains(env.IMAGE_PLATFORMS, ',')
        uses: docker/setup-qemu-action@v3
        timeout-minutes: 5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 5

      - name: Extract metadata for Docker
        id: docker-meta
        uses: docker/metadata-action@v5
        timeout-minutes: 5
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        timeout-minutes: 5
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Git metadata
        id: git-meta
        timeout-minutes: 5
        run: |
          echo "BRANCH_OR_TAG_NORMALIZED_WITH_SHA=$(echo ${{ env.BRANCH_OR_TAG }} | tr '/' '-'),${{ env.COMMIT_SHA }}" >> $GITHUB_OUTPUT

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        timeout-minutes: 50
        with:
          context: .
          push: true
          provenance: false
          build-args: |
            VERSION_SHA=${{ steps.git-meta.outputs.BRANCH_OR_TAG_NORMALIZED_WITH_SHA }}
          # https://github.com/docker/build-push-action/issues/545
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          platforms: ${{ env.IMAGE_PLATFORMS }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
